### ISSUE TITLE
Board class

### ISSUE THREAD

**Issue by edmachine** [NickLarson/PyCheckers#1]
Yo, figure out the board layout and board class initialization bro, and then code it up!

**Comment by NickLarson** [comment]
Not sure how to do graphics or what graphics library to use for it... or are
we talking non graphics?

**Comment by edmachine** [comment]
non graphics to start! the last milestone is for graphics. we have 3 weeks!

**Comment by edmachine** [comment]
didnt mean to close. lol

**Comment by edmachine** [comment]
so... the idea is that we have a class the represents the board, so we can use it within any program. the board initialization should be a constructor that takes in 2 integers for the size of the board.

We can do the board any number of ways, we could do it as a dictionary of dictionaries (IE: A-H for rows, and 1-8 for columns), or we could do a single list, or lists of lists. If we do it as a single list then we have to have a numbering convention, ie 1-64 for moving, but for checking for a legal move this is VERY difficult and makes it WAY less dynamic. if we do the dict of dicts then we can limit it to +/-1, and +/- a letter and movement checks are significantly easier. That is the main reason why I want to do it that way. it also means that accessing we do: board[A][1] to board[A][2] returns the move, and board[A][1] to board[D][3] returns False. We have to think about those things before just coding up a board to use.

**Comment by edmachine** [comment]
The board class will also need a piece class, which for checkers will contain just a color and type. The color is black or red, the type is regular or kinged (these should not be binary or ints, they should be strings, for ease of knowing what we are programming).
