### ISSUE TITLE
gui library

### ISSUE THREAD

**Issue by edmachine** [NickLarson/PyCheckers#2]
So... python has a massive amount of libraries, and we need to pick one for the graphics portion of the program...

http://wiki.python.org/moin/GuiProgramming

There are about 50-60 libraries to chose from (common issue in python), and so we should start looking into each of them to see which fits our needs. I would suggest a cross-platform library such as wxPython, libavg, pyglet, PyMT, TkInter, Kivy, etc. I would like the code for graphics to work on all major platforms (windows, linux, and mac), and it will also present a difficult task to find a good library for us to use. (wxPython is one of the best known ones, and same with Tkinter.)

**Comment by NickLarson** [comment]
I've briefly used wxPython... We could use that... I've also used
TWItter a little bit but it's entirely up to you!

On 8/27/11, edmachine
reply@reply.github.com
wrote:

> So... python has a massive amount of libraries, and we need to pick one for
> the graphics portion of the program...
> 
> http://wiki.python.org/moin/GuiProgramming
> 
> There are about 50-60 libraries to chose from (common issue in python), and
> so we should start looking into each of them to see which fits our needs. I
> would suggest a cross-platform library such as wxPython, libavg, pyglet,
> PyMT, TkInter, Kivy, etc. I would like the code for graphics to work on all
> major platforms (windows, linux, and mac), and it will also present a
> difficult task to find a good library for us to use. (wxPython is one of the
> best known ones, and same with Tkinter.)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NickLarson/PyCheckers/issues/2

## 

---

NICHOLAS S. LARSON, Cadet, AFROTC
Cyber Squadron
415th Cadet Wing, U of MN - Twin Cities
(651)-380-3692
lars4045@umn.edu

**Comment by edmachine** [comment]
Lets do wxPython for giggles as I have never done a GUI application. :)

**Comment by NickLarson** [comment]
Alright lol sounds good... My monitor is going to arrive on Tuesday
then I can begin actually working on it... Until then I can get basic
stuff down and read a little up on different things that might be
helpful.  I really don't feel like coding on my tablet so hopefully
that works!

On 8/27/11, edmachine
reply@reply.github.com
wrote:

> Lets do wxPython for giggles as I have never done a GUI application. :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NickLarson/PyCheckers/issues/2#issuecomment-1921275

## 

---

NICHOLAS S. LARSON, Cadet, AFROTC
Cyber Squadron
415th Cadet Wing, U of MN - Twin Cities
(651)-380-3692
lars4045@umn.edu
